[BRE-101] Remove dept-devops from CODEOWNERS
bitwarden/splunk pull request #44
Opened 2024-06-07 15:18 UTC by michalchecinski

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/BRE-101

## 📔 Objective

Remove `dept-devops` from CODEOWNERS.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-10 22:37 UTC, eliykat commented
@michalchecinski is this PR still required, or can it be closed?

2024-10-15 12:43 UTC, michalchecinski commented
@eliykat It's still required, I just updated it as we resumed work on this issue.

2024-10-16 18:27 UTC, vgrassia requested changes

2024-10-16 18:27 UTC, vgrassia commented on .github/CODEOWNERS
> +.github/workflows/build.yml @bitwarden/team-admin-console-dev
```suggestion
# Shared workflows ownership
.github/workflows/build.yml @bitwarden/dept-bre @bitwarden/team-admin-console-dev
```

2024-10-17 14:20 UTC, vgrassia approved these changes

2024-10-18 03:50 UTC, eliykat approved these changes

2024-10-18 03:50 UTC, merged