Improve readme
bitwarden/splunk pull request #54
Opened 2024-07-17 04:45 UTC by eliykat

## 🎟️ Tracking

N/A

## 📔 Objective

I set up the Splunk app for local development today and hit a few pain points, possibly because I'm not familiar with the Python ecosystem. In particular:
* forcing Docker to use the `linux/amd64` version of the Splunk image
* finding the right Python version and telling Poetry to use it
* installing libmagic, which is not installed by default

I've also restructured the instructions to be more step-by-step.

Two follow-up questions:
1. are there any objections to me moving these contributing instructions to contributing.bitwarden.com where the rest of our documentation lives?
2. `pyproject.toml` specifies the python version as `python = ">=3.7.17"`, however these instructions refer to Python 3.8 specifically. I received [syntax errors](https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp) when trying to use 3.12, which is what I already had installed on my system. I suggest we probably need to specify `^3.8` - what do you think @WaciX ?

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-17 08:05 UTC, mzieniukbw requested changes
Great changes! I have added few comments from me that makes it even better.

Answers to the follow-up questions:
- I am fine with moving the contributing instructions to https://contributing.bitwarden.com/.
- The 3.7 is EOL, so from development perspective it make sense to upgrade it, but we can't. Python version have to be locked to 3.7, because Splunk Enterprise works for 3.7 only at this moment and there are at least 2 more years of support for the app on those versions. Their newer release (in beta) brings support to 3.9, but it might take a while. I have not tested newer versions of python. We allow for ranges from 3.7, because it's easier from development perspective and we prepare for the splunk enteprise new release thart brings 3.9 support. Making it easier from development perspective, so 3.10 or newer can be used is a separate initiative.

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +2. Install Python 3.8
it's actually 3.7 or newer, but since 3.7 is EOL it might be hard to install. I have tested 3.7, 3.8 and 3.9:
```suggestion
2. Install Python 3.8 or 3.9
```

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +4. If you're using a Mac, install libmagic: `brew install libmagic`
```suggestion
4. If you're using a macOS, install libmagic: `brew install libmagic`
```

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +2. If you're using an Apple Silicon Mac, open *Docker* -> *Settings* -> *Features in development* -> enable "Use Rosetta for x86/amd64 emulation on Apple Silicon"
I newer Docker Desktop, it got moved from features in development to General
```suggestion
2. If you're using an Apple Silicon Mac, open *Docker Desktop* -> *Settings* -> *General* -> enable "Use Rosetta for x86_64/amd64 emulation on Apple Silicon"
```

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +3. Install [Poetry][poetry]
Prerequisites should be first in order, before cloning or navigating to directory

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +4. Navigate to your local repository
Please correct the numbers, we have two `4`s. Also it could be more explicit:
```suggestion
4. Navigate to your local repository: `cd splunk`
```

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +6. Tell poetry to use Python 3.8: `poetry env use python3.8`
Or 3.9, depends on what is installed.
Also it's worth to mention that the python version executable needs to be present in `PATH`. Otherwise absolute path to the python executable have to be specified.

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +1. Package the app: `./package.sh`
Maybe it's worth to mention that this script produces a packaged splunk application in this location: `output/bitwarden_event_logs.tar.gz`

2024-07-17 08:05 UTC, mzieniukbw commented on README.md
> +2. Deploy the app to Splunk: `./deploy.sh`
This script depends on splunk enterprise dunning in docker.
I think we should move the `### Set up Splunk Enterprise` to be before `### Deploy the app` but after `### Configure your environment`

Also the script have the splunk admin's password hardcoded to `password`, which we now say you can change to something rlse in the `### Set up Splunk Enterprise`. We should change the `deploy.sh` script to have ability to provide the password as argument (defaults to `password`).

Also it's worth to mention that the script restarts the splunk and it might become unavailable even after script finishes for few seconds.

2024-07-17 08:05 UTC, mzieniukbw commented on poetry.lock
there is no need to do it in this PR, since it would require QA testing. Let's leave this to https://github.com/bitwarden/splunk/pull/50 and revert this change.

2024-07-17 23:26 UTC, eliykat commented on poetry.lock
This was unintentional as I was messing around with my dependencies 😁

2024-07-17 23:52 UTC, eliykat commented
Thanks @mzieniukbw , I've continued these changes here: https://github.com/bitwarden/contributing-docs/pull/386

Once that's merged, we can just update this doc to link there.

Re: the Python version - can we specify that it should be `=< 3.9`? I was more concerned about limiting the use of newer, incompatible versions (3.12 threw errors) rather than bumping the min version (although I see that is what I wrote).

2024-08-15 23:59 UTC, eliykat commented
I like specifying it in pyproject.toml, it's an easy thing to miss and it's better to get an explicit error than some random runtime failure. I've done that and regenerated the lockfile as required. Now when I try with 3.12:

> Current Python version (3.12.4) is not allowed by the project (>=3.7.17, <=3.10).
> Please change python executable via the "env use" command.

I've also updated the README to point to the contributing docs.

2024-08-16 07:48 UTC, mzieniukbw approved these changes

2024-08-16 09:51 UTC, r-tome approved these changes

2024-08-18 21:54 UTC, merged